# QUERY VARIABLES
# {
#   "id": "115",
#   "teste":true
# }

query GET_USERS($id: ID! = "812") {
  user (id: $id) {
    id firstName lastName userName indexRef createdAt
  }
}

query GET_USERS($id: ID!, $teste: Boolean) {
  user (id: $id, teste: $teste) {
    id firstName lastName userName indexRef createdAt
  }
}

### Trivial Resolvers (unixTimestamp)
{
  posts {
    title
    createdAt
    unixTimestamp
  }
}
